### ISSUE TITLE
OLOF: One Link One File

### ISSUE THREAD

**Issue by jainanupam** [jainanupam/GitToPost#1]
There should be only one file per link. Currently we have one file per programming language.

**Comment by payamrastogi** [comment]
"one file per link" or one link per file. I'm not able to understand.
What's the actual reason behind this issue?

**Comment by jainanupam** [comment]
By file I meant one post for one problem. Say there is a question on leetcode which you've solved in Java and I did that in python. Currently we'll have two post files created for that same problem. I guess it would be better to have just one post with both solutions in the same post.

**Comment by jainanupam** [comment]
Issues seems resolved. Need further testing and approval. Closing!!
