### ISSUE TITLE
Identify posts which are uploaded.

### ISSUE THREAD

**Issue by jainanupam** [jainanupam/GitToPost#5]
@payamrastogi 
Could we have a mechanism to identify the posts which are already uploaded on coddicted?
One possible resolution is to move the post file to a designated directory after upload. Need to explore it further.

**Comment by payamrastogi** [comment]
another option is to maintain a list of filenames(hash values) of all the files which are downloaded and posted to coddicted. So we gonna download only those files which are not present in the list.

**Comment by jainanupam** [comment]
a. we are not downloading the files through this project.
b. Identifying which files have been posted is the core of the issue.
c. Deadpool is cool with quite obscene language.

**Comment by jainanupam** [comment]
Added code changes for the issue. Commit number: 469f18fc725264bc914ac6a2453832cf01ae0fd1
